print("Hello,World")
print("Raahim")
print("Raahim","Khan")
print(123)
print("Hello \nWorld")
print("hello \t World")
print("apple","banana","cherry",sep="," )
print(1,2,3,sep="-")
print("Hello", end=" ")
print("World")
print(1, end='')
print(2)
print("He said ,\"Hello!\"")
print("This is a: \\")
print(f"I am",20,"years")
print(f"The number is",5)
for x in range(1,6,1):
    print(x)